### Generic smell configuration

### Directory specific configuration

# Includes recommended Rails configuration.
directories:
  "app/controllers":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    InstanceVariableAssumption:
      enabled: false
  "app/graphql":
    UtilityFunction:
      enabled: false
  "app/helpers":
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/mailers":
    InstanceVariableAssumption:
      enabled: false
  "app/models":
    InstanceVariableAssumption:
      enabled: false
  "app/workers/**":
    UtilityFunction:
      enabled: false
  "lib/middleware":
    InstanceVariableAssumption:
      enabled: false

### Excluding directories

# Directories and files below will not be scanned at all.
exclude_paths:
  - lib/generators/
  - db/
  - config/
  - spec/
  - bin/
